export class User {
    _id: string;
    username: string;
    password: string;
    firstName: string;
    lastName: string;
	email: string;
	phone: string;
	designation: string;
	company_name: string;
	user_role: string;
	employee_id:string;
	admin_id:string;
	email_company: string;
	emergency_contact_person: string;
	emergency_contact_person_phone: string;
	current_address: string;
	permanent_address: string;
	pan_no: string;
	passport_no: string;
	father_name: string;
	spouse_name: string;
	date_of_joining: string;
	date_of_birth: string;
	years_of_exp: number;
	mediclaim: boolean;
	number_of_dependents: number;
	married: boolean;
	bank_name: string;
	bank_account_number: string;
	bank_IFSC_code: string;
	bank_branch_address: string;
	bank_city: string;
	bank_state: string;
	highest_education: string;
	final_degree_perc: number;
	degree_spec: string;
	college_name: string;
	university_name: string;
	attendance_id: number;
}